apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: suryanshu185/vprofiledb:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-07aeb28a80553b038
            fsType: ext4
      nodeSelector:
        zone: us-east-1a
